#!/bin/sh
# Docker sandbox entrypoint for MulmoTerminal.
#
# Runs as root to perform setup steps that require elevated privileges,
# then drops to the host user's UID:GID via setpriv (part of util-linux,
# already in node:22-slim — no extra install).
#
# In the default path MulmoTerminal starts the container with
# `--user ${UID}:${GID}` and does NOT set HOST_UID, so this script just
# execs the command. The root-setup branch below is dormant until SSH
# agent forwarding is wired up (it sets HOST_UID), at which point the
# entrypoint fixes /etc/passwd + the agent socket and drops privileges.

set -e

# When HOST_UID is unset, the container was started with `--user`
# (non-SSH mode). Skip all root setup and exec directly — we're
# already running as the target user with zero capabilities.
if [ -z "${HOST_UID:-}" ]; then
  exec "$@"
fi

TARGET_UID="$HOST_UID"
TARGET_GID="${HOST_GID:-1000}"

# 1. Add a /etc/passwd entry for the target UID if it doesn't exist.
#    SSH refuses to operate when the running user has no passwd entry
#    ("No user exists for uid NNN"). On macOS the host UID is
#    typically 501, which isn't in the container's passwd (only root=0
#    and node=1000 are).
if ! getent passwd "$TARGET_UID" > /dev/null 2>&1; then
  echo "sandbox:x:${TARGET_UID}:${TARGET_GID}::/home/node:/bin/sh" >> /etc/passwd
fi

# 1b. Ensure /home/node is writable by the target user.
chown -R "$TARGET_UID:$TARGET_GID" /home/node 2>/dev/null || true

# 2. Make the SSH agent socket accessible to the target user.
if [ -S "${SSH_AUTH_SOCK:-}" ]; then
  chmod 666 "$SSH_AUTH_SOCK" 2>/dev/null || true
fi

# 3. Restrict SSH agent usage to whitelisted hosts only.
#    SANDBOX_SSH_ALLOWED_HOSTS: comma-separated list of hostnames.
#    Default: github.com.
if [ -S "${SSH_AUTH_SOCK:-}" ]; then
  ALLOWED_HOSTS="${SANDBOX_SSH_ALLOWED_HOSTS:-github.com}"
  SSH_DIR="/home/node/.ssh"
  SSH_CONFIG="${SSH_DIR}/config"

  mkdir -p "$SSH_DIR"
  # SSH uses first-match-wins, so whitelisted hosts MUST come BEFORE
  # the catch-all `Host *` block.
  cat > "$SSH_CONFIG" <<SSHEOF
# Auto-generated by sandbox-entrypoint.sh — do not edit.
# Restrict SSH agent forwarding to whitelisted hosts only.
# Override via SANDBOX_SSH_ALLOWED_HOSTS env var.

SSHEOF

  # Per-host overrides FIRST (most-specific → least-specific)
  echo "$ALLOWED_HOSTS" | tr ',' '\n' | while read -r host; do
    host=$(echo "$host" | tr -d ' ')
    if [ -n "$host" ]; then
      printf "Host %s\n  IdentityAgent %s\n  StrictHostKeyChecking accept-new\n\n" "$host" "$SSH_AUTH_SOCK" >> "$SSH_CONFIG"
    fi
  done

  # Catch-all LAST: block agent for everything else
  cat >> "$SSH_CONFIG" <<SSHEOF
Host *
  IdentityAgent none
  StrictHostKeyChecking accept-new
SSHEOF

  chmod 700 "$SSH_DIR"
  chmod 600 "$SSH_CONFIG"
  chown -R "${TARGET_UID}:${TARGET_GID}" "$SSH_DIR"
fi

# 4. Drop privileges and exec the actual command (typically `claude`).
exec setpriv --reuid="$TARGET_UID" --regid="$TARGET_GID" --init-groups --inh-caps=-all -- "$@"
