// MCP tool binding for the shared `manageCollection` agent data plane
// (@mulmoclaude/core/collection/server — the same engine MulmoClaude's host
// binds). Registered as a HOST TOOL (see host-tools.ts + the
// /api/plugin/manageCollection dispatch route in server/index.ts): the engine
// runs in-process against the shared workspace, so unlike manageAccounting
// there is no passthrough router — the route calls the handler directly.
//
// MulmoTerminal's deps binding:
//   - workspaceRoot: a GETTER over the bound workspace, not a captured string. The tool
//     is built at module scope — before boot binds anything — so a value read here would
//     be `undefined`, and under the engine's explicit-root binding that is a throw rather
//     than a fallback. The getter defers the read to the call, which is when a root exists.
//     (This is the agent's data plane, which has no request: it operates on the workspace.)
//   - bundledHelpsDir: workspace-setup's helpsAssetDir, so `schemaDocs`
//     serves the bundled collection-authoring reference even when the
//     workspace has no config/helps copy (only managed workspaces are seeded).
//   - refreshAfterWrite: omitted — MulmoTerminal has no schema-driven side
//     state to refresh after putSchema (MulmoClaude refreshes its scheduled
//     skills / user tasks); collection watchers pick up the write via fs events.
import type { ToolDefinition } from "gui-chat-protocol";
import { makeManageCollectionTool } from "@mulmoclaude/core/collection/server";
import { helpsAssetDir } from "@mulmoclaude/core/workspace-setup";
import { workspaceScope } from "./project-root.js";
import { isManagedWorkspace } from "../backends/workspaceSetup.js";
// A successful `putSchema` carries back whether the collection would survive a clone — the agent
// is the one that chose the storage kind or dropped the primaryKey, and it is holding the file
// open at the moment that is cheapest to fix.
import { withPortabilityNote } from "./collectionToolPortability.js";
// A shared collection's schema is refused unless its `app.json` already declares an `aid`, and the
// aid is generated by code (D2b) — so it is generated on the way IN, at the moment the agent
// writes the schema, rather than at the first deploy.
import { withGeneratedAid } from "./collectionToolAid.js";
// A `putItems` into a collection whose app declares a `stampField` is refused by the deployed
// rules whatever it sends — the server owns that value — so it is refused here instead, with the
// path that does work.
import { withStampGuard } from "./collectionToolStamp.js";

const tool = makeManageCollectionTool({
  bundledHelpsDir: helpsAssetDir,
  get workspaceRoot(): string {
    return workspaceScope().workspaceRoot;
  },
});

/** The bound handler the dispatch route calls. Returns the tool's narration
 *  string (JSON for the read/write actions) — no GUI `data`, matching
 *  MulmoClaude where manageCollection results narrate to claude only.
 *
 *  This one is the AGENT's data plane and operates on the workspace, which is what the
 *  getter above says. A REQUEST must not use it — see `manageCollectionHandlerFor`. */
export const manageCollectionHandler = withGeneratedAid(
  withStampGuard(
    withPortabilityNote(tool.handler, () => workspaceScope().workspaceRoot),
    () => workspaceScope().workspaceRoot,
  ),
  () => workspaceScope().workspaceRoot,
);

// One tool instance per root. `makeManageCollectionTool` takes its root in the FACTORY deps,
// not per call, so a request-scoped operation needs its own instance; they are cached because
// a custom view's dashboard can issue these in a loop. Bounded by the number of projects the
// user has, which is the same list `resolveProjectRoot` resolves against.
const byRoot = new Map<string, typeof tool.handler>();

/** The handler bound to ONE project root — what a request-scoped route must use.
 *
 *  The workspace-bound handler above would execute against the workspace no matter which
 *  project the request named and its token was checked for, so a view in one project could
 *  receive another's rows for a shared slug. The token check and the query have to agree on
 *  the root, and this is how the query learns it. */
export function manageCollectionHandlerFor(workspaceRoot: string): typeof tool.handler {
  const cached = byRoot.get(workspaceRoot);
  if (cached) return cached;
  const handler = withGeneratedAid(
    withStampGuard(
      withPortabilityNote(
        makeManageCollectionTool({
          bundledHelpsDir: helpsAssetDir,
          workspaceRoot,
          // Which authoring guide `schemaDocs` serves. Staged authoring (`data/skills/<slug>/`,
          // mirrored by a bridge) is a WORKSPACE mechanism; told that in a project folder, the agent
          // writes a draft nothing mirrors and nothing discovers — it does as instructed and produces
          // a collection that does not exist, with no error anywhere.
          //
          // The engine also derives the variant from `skillsStagingDir` returning null, so this
          // agrees with the host binding rather than overriding it. Passed anyway: two levers that
          // must agree are worth stating at both ends, and this one says WHY the root has no staging
          // rather than leaving it to be inferred from a path that came back empty.
          stagedSkillAuthoring: isManagedWorkspace(workspaceRoot),
        }).handler,
        () => workspaceRoot,
      ),
      () => workspaceRoot,
    ),
    () => workspaceRoot,
  );
  byRoot.set(workspaceRoot, handler);
  return handler;
}

/** gui-chat-protocol shape of the core tool's MCP definition — the same
 *  inputSchema→parameters / prompt-folding adaptation loadServerToolPackage
 *  applies to XTool-shaped server tools. The core definition types its
 *  inputSchema loosely (`type: string`); the runtime value is the literal
 *  "object" the protocol type wants, so re-stamp it. */
// Annotated, not asserted: the spread widens `type` back to `string`, and an annotation makes the
// compiler check the result against what the protocol wants instead of being told.
const collectionToolParameters: NonNullable<ToolDefinition["parameters"]> = { ...tool.definition.inputSchema, type: "object" };

export const MANAGE_COLLECTION: ToolDefinition = {
  type: "function",
  name: tool.definition.name,
  description: tool.definition.description,
  prompt: tool.prompt,
  parameters: collectionToolParameters,
};
