// Per-session state every layer reads: the routes answering /api/sessions, the WebSocket
// handlers, the Claude hooks, and the PTY spawns all reach for the same tables. They lived
// in index.ts, which is why nothing else could be split out of it (#548) — a table here can
// be imported without importing the boot module.
//
// The maps are exported directly, not behind accessors: every call site already reads and
// writes them as maps, and wrapping ~150 of those in getters would be churn with no invariant
// to enforce. What DOES belong here is the persistence, because "what is on disk" and "what
// is in memory" have to agree.
import { promises as fs } from "node:fs";
import path from "node:path";
import { MULMOTERMINAL_HOME, SESSION_ID_RE } from "../config/env.js";
import { messageOf } from "../errors.js";
import { buildActivitySnapshot, parseActivityState } from "./activity-state.js";
import type { Activity, KnownSession, PtyEntry } from "./types.js";

// Per-session "working" state, driven by Claude hooks (see /api/hook):
// UserPromptSubmit => Claude started thinking; Stop => it finished.
export const activity = new Map<string, Activity>(); // id -> { working, event, at }

// Live ptys keyed by session id. A pty outlives its WebSocket while the session
// is still "working", so switching away doesn't interrupt Claude mid-turn; it
// is reaped once the session goes idle (Stop hook) or the process exits. `ws`
// is null while the session runs in the background.
export const ptys = new Map<string, PtyEntry>(); // id -> { term, ws, buffer }

// New sessions started in this process that have no .jsonl on disk yet (Claude
// only writes the file on the first prompt). Merged into /api/sessions so a
// freshly created session shows in the sidebar immediately. An entry is dropped
// once the file exists (the on-disk record takes over) or the pty is reaped.
export const knownSessions = new Map<string, KnownSession>(); // id -> { createdAt, title }

// Sessions spawned as hidden background workers (spawnBackgroundChat hidden:true).
// They list normally but never render bold/unread. Process-lifetime only (not
// persisted) — and tied to `activity`'s lifecycle in reap() so a finished hidden
// worker that stays `waiting` doesn't lose its hidden flag and re-bold.
export const hiddenSessions = new Set<string>(); // id

// Latest MEANINGFUL user prompt per session (from the UserPromptSubmit hook), shown
// on the grid cell header so you can tell at a glance what each terminal is about. A
// trivial ack ("ok", "merge") doesn't replace it (see the hook handler), so a short
// follow-up can't hide the task.
export const lastPrompts = new Map<string, string>(); // id -> prompt text

// AI header title per session (issue #316): a short summary of the recent turns that
// stays meaningful when the session turns into a back-and-forth, where the raw last
// prompt goes stale ("ok") or context-dependent ("2番目にして"). Generated by a cheap
// model, it takes precedence over lastPrompt in the cell header. Kept in memory (never
// written into Claude's transcript); a resumed session falls back to any on-disk title.
export const aiTitles = new Map<string, string>(); // id -> AI title

// the last few lines of the agent's most recent reply, refreshed when
// a turn ends (waiting), so the roster can show "what it just said" without the terminal open.
export const lastResponses = new Map<string, string>(); // id -> last assistant text (truncated)

export const titleTurnCounts = new Map<string, number>(); // id -> user turns since last title
export const titlePending = new Set<string>(); // ids whose next Stop should (re)generate a title
export const titleInFlight = new Set<string>(); // ids currently generating, to avoid overlap
export const titleEpoch = new Map<string, number>(); // bumped on /clear or teardown to void an in-flight generation
// The transcript's user-turn count when we last titled a session, so the roster's view-triggered
// re-titling knows when a session has advanced enough to be worth re-summarizing. Kept across
// /clear (dropped only on teardown) so a just-cleared session isn't re-titled from its frozen
// pre-clear transcript.
export const lastTitledUserTurns = new Map<string, number>();
// Wall-clock of the last view-triggered title attempt per session, so a session whose generation
// keeps failing backs off instead of re-spawning the summarizer on every 4s roster poll.
export const lastTitleAttemptMs = new Map<string, number>();

// mulmoterminal session key -> the codex rollout id it maps to. codex mints its own id, so we
// discover it after spawn and keep it here to `codex resume <id>` once the live PTY is gone.
export const codexRolloutIds = new Map<string, string>();
// Rollout files already attributed to a session, so a single rollout is never mapped to two keys
// (which would let both cold-resume the same conversation). Serialized by the single event loop.
export const claimedCodexRollouts = new Set<string>();

// Session ids that belong to the multi-terminal GRID — dev terminals, spawned with
// gui=0 (no GUI MCP; see the ?gui handling in the WS connection handler). They're
// FILTERED OUT of the chat sidebar's /api/sessions so a grid terminal never surfaces
// as a clickable chat row: selecting it in chat would reattach its live PTY and
// SUPERSEDE the grid cell (the "chat hijacked my multi-terminal session" bug). The
// set is persisted so the exclusion survives a reboot and outlives the live PTY — a
// reaped grid session's on-disk transcript still shouldn't reappear as a chat. NOTE:
// the exclusion applies ONLY to the unscoped (chat) query; the grid's OWN cwd-scoped
// resume picker (/api/sessions?cwd=…) must keep listing these so they stay resumable.
export const devTerminalSessions = new Set<string>();
const DEV_TERMINAL_SESSIONS_FILE = path.join(MULMOTERMINAL_HOME, "dev-terminal-sessions.json");

// Hydrate the set once at boot (best-effort — absent on first run / unreadable =>
// empty). Exposed as a promise so readers/writers can wait for it: a request served
// (or a mark persisted) before this resolves would otherwise see an empty set and
// either leak hidden grid transcripts into chat or clobber the file with a snapshot
// missing the on-disk ids.
export const devTerminalSessionsHydrated: Promise<void> = (async () => {
  try {
    const parsed = JSON.parse(await fs.readFile(DEV_TERMINAL_SESSIONS_FILE, "utf8"));
    if (Array.isArray(parsed)) for (const id of parsed) if (typeof id === "string" && SESSION_ID_RE.test(id)) devTerminalSessions.add(id);
  } catch {
    // no file yet or unreadable => start empty
  }
})();

// Serialize every persist into ONE chain so concurrent marks can't run overlapping
// writeFile()s that interleave and leave an older snapshot on disk (dropping ids).
// Each link waits for hydration first (so it never persists a set missing the on-disk
// ids) and stringifies the CURRENT set at write time, so the last link always writes
// the complete, up-to-date set. A failed write is logged and the chain continues.
let devTerminalPersist: Promise<void> = Promise.resolve();
function persistDevTerminalSessions(): void {
  devTerminalPersist = devTerminalPersist
    .then(() => devTerminalSessionsHydrated)
    .then(() => fs.mkdir(MULMOTERMINAL_HOME, { recursive: true }))
    .then(() => fs.writeFile(DEV_TERMINAL_SESSIONS_FILE, JSON.stringify([...devTerminalSessions])))
    .catch((e) => console.error(`[dev-terminal-sessions] failed to persist: ${messageOf(e)}`));
}

// Record a grid/dev-terminal session id, then persist. A no-op once the id is known,
// so repeated reattaches of the same cell — or a reconnect after a reboot — don't
// rewrite the file.
export function markDevTerminalSession(id: string): void {
  if (!SESSION_ID_RE.test(id) || devTerminalSessions.has(id)) return;
  devTerminalSessions.add(id);
  persistDevTerminalSessions();
}

// Restore the `working` + blocked/done (`waiting`) flags across a server restart (e.g. a
// --watch hot reload), so a live session doesn't reattach as idle. `waiting` matters because
// Claude won't re-fire Notification while already sitting at a prompt; `working` because a
// turn usually outlives the ~1s restart and its later Stop hook self-corrects a stale flag
// (the only stale case is a turn that finished DURING the restart window — corrected on the
// user's next turn). Read paths await hydration (see /api/activity, /api/session) so a
// reconnect re-fetch can't race it back to idle. Mirrors the dev-terminal-sessions pattern.
const ACTIVITY_STATE_FILE = path.join(MULMOTERMINAL_HOME, "activity-state.json");
export const activityStateHydrated: Promise<void> = (async () => {
  try {
    const parsed = JSON.parse(await fs.readFile(ACTIVITY_STATE_FILE, "utf8"));
    for (const { id, working, waiting, event } of parseActivityState(parsed, (x) => SESSION_ID_RE.test(x))) {
      // Don't clobber a live update that already landed while hydration was in flight.
      if (!activity.has(id)) activity.set(id, { working, waiting, event, at: Date.now() });
    }
  } catch {
    // no file yet / unreadable => nothing to restore
  }
})();

// Serialize writes into one chain (like persistDevTerminalSessions) and snapshot the
// CURRENT working/waiting entries at write time, so the last link always writes the complete set.
// `isHidden` comes from the caller rather than closing over `hiddenSessions`: which sessions
// are hidden is the session layer's policy, and this module owns storage, not policy.
let activityPersist: Promise<void> = Promise.resolve();
export function persistActivityState(isHidden: (id: string) => boolean): void {
  activityPersist = activityPersist
    .then(() => activityStateHydrated)
    .then(() => fs.mkdir(MULMOTERMINAL_HOME, { recursive: true }))
    .then(() => fs.writeFile(ACTIVITY_STATE_FILE, JSON.stringify(buildActivitySnapshot(activity, isHidden))))
    .catch((e) => console.error(`[activity-state] failed to persist: ${messageOf(e)}`));
}
