// @vitest-environment node
//
// The `aid` is generated by CODE, not by the agent (design D2b) — so what this pins is that the
// generator behaves like one: it mints exactly once, it keeps what the author wrote, and it
// refuses rather than inventing a declaration.
import { describe, it, expect, beforeEach } from "vitest";
import { chmodSync, lstatSync, readFileSync, readdirSync, statSync, symlinkSync, writeFileSync } from "node:fs";
import path from "node:path";
import { ensureAid, requireAid } from "../../../server/backends/sharedApp/ensureAid.js";
import { makeTempDir } from "../../support/tempDir";

let root = "";
const appJson = (): string => path.join(root, "app.json");
const read = (): Record<string, unknown> => JSON.parse(readFileSync(appJson(), "utf-8"));

describe("ensureAid", () => {
  beforeEach(() => {
    root = makeTempDir("mt-ensure-aid-");
  });

  it("mints a uuid when app.json has none, and keeps everything else the author wrote", () => {
    writeFileSync(appJson(), JSON.stringify({ name: "Sakura", members: { "owner@example.com": { "*": "owner" } } }));
    return ensureAid(root).then((result) => {
      expect(result.ok && result.created).toBe(true);
      // A UUID, not a memorable name: `apps/{aid}` is a shelf every user shares and a memorable
      // id is first-come-first-served (D2b).
      expect(result.ok && result.aid).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/);
      const written = read();
      expect(written.aid).toBe(result.ok && result.aid);
      expect(written.name).toBe("Sakura");
      expect(written.members).toEqual({ "owner@example.com": { "*": "owner" } });
    });
  });

  it("keeps the aid it already has — the id is the app's identity, not a per-run value", async () => {
    writeFileSync(appJson(), JSON.stringify({ aid: "already-there", name: "Sakura" }, null, 2));
    const first = await ensureAid(root);
    expect(first.ok && first.aid).toBe("already-there");
    expect(first.ok && first.created).toBe(false);
    // Twice, because "mints every time" and "mints once" look identical on a single call.
    const second = await ensureAid(root);
    expect(second.ok && second.aid).toBe("already-there");
  });

  it("refuses a missing app.json rather than writing one", async () => {
    const result = await ensureAid(root);
    expect(result.ok).toBe(false);
    // Writing a bare `{ aid }` would turn a mistyped path into an app declaration.
    expect(result.ok === false && result.problems.join(" ")).toContain("app.json");
    expect(() => readFileSync(appJson(), "utf-8")).toThrow();
  });

  it("refuses a broken app.json rather than replacing it", async () => {
    writeFileSync(appJson(), "{ not json");
    const result = await ensureAid(root);
    expect(result.ok).toBe(false);
    expect(readFileSync(appJson(), "utf-8")).toBe("{ not json");
  });

  it("leaves no scratch file behind, and never a half-written declaration", async () => {
    // The file it would destroy is the author's declaration — the roster and the public settings —
    // and nothing here could put it back, so the new one is written beside it and renamed into
    // place. What that has to be checked for is the litter: a scratch file left in the repository
    // is a file someone commits.
    writeFileSync(appJson(), JSON.stringify({ name: "Sakura" }));
    const result = await ensureAid(root);
    expect(result.ok).toBe(true);
    expect(readdirSync(root)).toEqual(["app.json"]);
  });

  // Skipped on Windows, the way session-settings.spec.ts skips its owner-only check: NTFS has no
  // POSIX permission bits, so `chmodSync(file, 0o600)` moves the read-only attribute and nothing
  // else, and the mode reads back 0o666. The setup cannot establish the precondition there, so
  // the assertion tests nothing — it just goes red (0o666 vs 0o600).
  it.skipIf(process.platform === "win32")("keeps the mode the author gave app.json", async () => {
    // The replacement is a new file, so it carries this process's umask unless something says
    // otherwise. A manifest deliberately kept at 0600 coming back 0644 is a permission change
    // nobody asked for and nothing reports.
    writeFileSync(appJson(), JSON.stringify({ name: "Sakura" }));
    chmodSync(appJson(), 0o600);
    expect((await ensureAid(root)).ok).toBe(true);
    expect(statSync(appJson()).mode & 0o777).toBe(0o600);
  });

  it("mints ONE aid when two calls race", async () => {
    // Read-mint-write is three steps. Interleaved, both callers see "no aid", mint different
    // uuids, and each renames its own file — and the loser is the one that goes on to create an
    // app document, leaving a live apps/{uuid} the declaration no longer names.
    writeFileSync(appJson(), JSON.stringify({ name: "Sakura" }));
    const results = await Promise.all([ensureAid(root), ensureAid(root), ensureAid(root)]);
    const aids = new Set(results.map((result) => (result.ok ? result.aid : "failed")));
    expect(aids.size).toBe(1);
    // And exactly one of them did the writing.
    expect(results.filter((result) => result.ok && result.created)).toHaveLength(1);
    expect([...aids][0]).toBe(read().aid);
  });

  it("serializes two SPELLINGS of the same root, not two strings", async () => {
    // A root arrives as the session's cwd, taken verbatim — so one cell opened at a symlink and
    // another at its target name the same app.json two ways. Keyed on the spelling, that is two
    // chains, which is the interleaving the serializer exists to prevent with the lock quietly
    // not held.
    writeFileSync(appJson(), JSON.stringify({ name: "Sakura" }));
    const alias = path.join(makeTempDir("mt-ensure-aid-alias-"), "link");
    symlinkSync(root, alias);

    const results = await Promise.all([ensureAid(root), ensureAid(alias), ensureAid(path.join(root, "."))]);
    expect(new Set(results.map((result) => (result.ok ? result.aid : "failed"))).size).toBe(1);
    expect(results.filter((result) => result.ok && result.created)).toHaveLength(1);
    expect(results[0]?.ok === true && results[0].aid).toBe(read().aid);
  });

  it("updates the file a linked app.json points at, and leaves the link a link", async () => {
    // `readFile` follows a symlink and `rename` replaces one, so writing beside the NAME would
    // read the shared declaration through the link and then overwrite the link with a detached
    // copy — the target never gets the aid, and whoever else reads the target sees a different
    // app from the one this repository just deployed.
    const shared = path.join(makeTempDir("mt-ensure-aid-shared-"), "app.json");
    writeFileSync(shared, JSON.stringify({ name: "Shared" }));
    symlinkSync(shared, appJson());

    const result = await ensureAid(root);
    expect(result.ok).toBe(true);
    expect(JSON.parse(readFileSync(shared, "utf-8")).aid).toBe(result.ok && result.aid);
    expect(lstatSync(appJson()).isSymbolicLink()).toBe(true);
  });

  it("refuses a JSON file that is not an object", async () => {
    writeFileSync(appJson(), "[]");
    expect((await ensureAid(root)).ok).toBe(false);
  });
});

describe("requireAid", () => {
  beforeEach(() => {
    root = makeTempDir("mt-require-aid-");
  });

  it("hands back the aid the declaration already has, and writes nothing", async () => {
    writeFileSync(appJson(), JSON.stringify({ aid: "already-there", name: "Sakura" }, null, 2));
    const before = readFileSync(appJson(), "utf-8");

    const result = await requireAid(root);
    expect(result.ok && result.aid).toBe("already-there");
    expect(result.ok && result.created).toBe(false);
    // Byte for byte: this is the read half of the pair, and a formatting rewrite of a committed
    // file is a diff the author did not ask for.
    expect(readFileSync(appJson(), "utf-8")).toBe(before);
  });

  it("refuses a declaration with no aid instead of minting one — that would publish a SECOND app", async () => {
    // The failure this exists for: an agent clears the `aid` to "start over", publish mints a new
    // one, and the app everybody's records are in is left behind with nothing pointing at it.
    writeFileSync(appJson(), JSON.stringify({ name: "Sakura", members: { "owner@example.com": { "*": "owner" } } }));

    const result = await requireAid(root);
    expect(result.ok).toBe(false);
    expect(result.ok === false && result.problems.join(" ")).toMatch(/declares no `aid`/);
    // And it stays refused: nothing was written, so a second run says the same thing rather than
    // finding an id this one left.
    expect(read()).not.toHaveProperty("aid");
    expect((await requireAid(root)).ok).toBe(false);
  });

  it("refuses an empty aid the same way — a blank string is a lost id, not an app", async () => {
    writeFileSync(appJson(), JSON.stringify({ aid: "", name: "Sakura" }));
    expect((await requireAid(root)).ok).toBe(false);
  });
});
