<script setup lang="ts">
// Read-only render of one wiki page: sanitized markdown body with clickable
// `[[wiki links]]`, rewritten image refs, and a "Linked references" (backlinks)
// section derived from the shared graph. Navigation is delegated up via the
// useWikiBrowse helpers — clicking a link/backlink pushes /wiki/pages/<slug>.
import { computed } from "vue";
import { resolveLinkTarget, wikiSlugify, isSafeWikiSlug, incomingLinks, type WikiGraph } from "@mulmoclaude/core/wiki";
import { renderWikiHtml } from "../wikiMarkdown";
import { wikiGotoPage } from "../composables/useWikiBrowse";
import type { WikiPage } from "../wikiApi";

const props = defineProps<{ slug: string; page: WikiPage; graph: WikiGraph | null }>();

const html = computed(() => (props.page.exists ? renderWikiHtml(props.page.content) : ""));

// Title→slug map keyed by the EXACT graph title: core's resolveLinkTarget looks up
// `slugByTitle.get(target.trim())` with the raw (non-lowercased) target after slug
// matching, so the keys must match the server graph's titles verbatim — otherwise a
// mixed-case title whose slug differs from its slugified form (e.g. "Foo Bar" →
// meeting-notes-2026) would fail to resolve on click.
const fileSlugs = computed(() => new Set((props.graph?.nodes ?? []).map((n) => n.slug)));
const slugByTitle = computed(() => new Map((props.graph?.nodes ?? []).map((n) => [n.title, n.slug])));
const backlinks = computed(() => (props.graph ? incomingLinks(props.graph, props.slug) : []));

// Resolve a `[[link]]` span's raw target to a file slug (graph first, then a plain
// slugify fallback) and navigate.
function activateLink(el: HTMLElement | null): void {
  const target = el?.getAttribute("data-page");
  if (!target) return;
  let slug = props.graph ? resolveLinkTarget(target, fileSlugs.value, slugByTitle.value) : null;
  if (!slug) {
    const fallback = wikiSlugify(target);
    slug = isSafeWikiSlug(fallback) ? fallback : null;
  }
  if (slug) wikiGotoPage(slug);
}

// Mouse + keyboard activation, both event-delegated over the rendered body. The spans
// carry role="link" + tabindex="0" (added in renderWikiHtml) so they're focusable.
function onBodyClick(e: MouseEvent): void {
  const el = (e.target as HTMLElement).closest<HTMLElement>(".wiki-link");
  if (!el) return;
  e.preventDefault();
  activateLink(el);
}
function onBodyKeydown(e: KeyboardEvent): void {
  if (e.key !== "Enter" && e.key !== " ") return;
  const el = (e.target as HTMLElement).closest<HTMLElement>(".wiki-link");
  if (!el) return;
  e.preventDefault();
  activateLink(el);
}
</script>

<template>
  <article class="mx-auto max-w-[820px] px-7 pt-6 pb-16 text-fg">
    <template v-if="page.exists">
      <h1 class="mb-4 text-[24px] font-bold">{{ page.resolvedTitle }}</h1>
      <!-- eslint-disable-next-line vue/no-v-html -- LLM-authored, sanitized in renderWikiHtml -->
      <div class="wiki-body text-[14px] leading-[1.65]" @click="onBodyClick" @keydown="onBodyKeydown" v-html="html"></div>
      <section v-if="backlinks.length" class="mt-10 border-t border-border pt-4">
        <h2 class="mb-2 text-[13px] uppercase tracking-[0.04em] text-muted">Linked references</h2>
        <ul class="m-0 list-none p-0">
          <li v-for="node in backlinks" :key="node.slug">
            <button
              type="button"
              class="cursor-pointer border-0 bg-transparent px-0 py-0.5 text-[14px] text-accent hover:underline"
              @click="wikiGotoPage(node.slug)"
            >
              {{ node.title }}
            </button>
          </li>
        </ul>
      </section>
    </template>
    <p v-else class="px-7 py-12 text-center text-muted">Page “{{ slug }}” not found.</p>
  </article>
</template>

<!-- Only the v-html markdown body stays scoped: its elements are generated by
     renderWikiHtml, so they can't carry utilities and must be reached via :deep. -->
<style scoped>
.wiki-body :deep(h1),
.wiki-body :deep(h2),
.wiki-body :deep(h3) {
  margin: 1.4em 0 0.5em;
  font-weight: 650;
}
.wiki-body :deep(a) {
  color: var(--accent);
}
.wiki-body :deep(code) {
  background: var(--bg-subtle);
  padding: 0.1em 0.35em;
  border-radius: 4px;
  font-size: 0.9em;
}
.wiki-body :deep(pre) {
  background: var(--bg-subtle);
  padding: 12px 14px;
  border-radius: 8px;
  overflow-x: auto;
}
.wiki-body :deep(img) {
  max-width: 100%;
  height: auto;
}
.wiki-body :deep(blockquote) {
  margin: 1em 0;
  padding-left: 12px;
  border-left: 3px solid var(--border);
  color: var(--text-secondary);
}
/* Clickable [[wiki links]] (spans from core's renderWikiLinks). */
.wiki-body :deep(.wiki-link) {
  color: var(--accent);
  cursor: pointer;
  border-bottom: 1px dotted var(--accent);
}
</style>
